import type { Metadata } from 'next';
import './globals.css';
import { Rubik } from 'next/font/google';
const rubik = Rubik({ subsets: ['latin', 'arabic', 'cyrillic', 'hebrew', 'cyrillic-ext'], variable: '--font-rubik' });
import { open_sans } from '@/utils/fontUtils';

export const metadata: Metadata = {
  title: 'Restaurant Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} ${rubik.variable} ${open_sans.variable} bg-yellow-50 h-screen overflow-hidden text-black-500`}
      >
        {children}
      </body>
    </html>
  );
}
